package textdata

var RightAnsw = "✅Правильный ответ!\nДля продолжения решения нажми на кнопку заданий"

var Answ = map[string]string{
	"маленькая":    RightAnsw,
	"отказываюсь":  RightAnsw,
	"мусор":        RightAnsw,
	"глазунья":     RightAnsw,
	"яичница":      RightAnsw,
	"пограничники": RightAnsw,
	"лейкоциты":    RightAnsw,
	"легче сказать, чем сделать":  RightAnsw,
	"разговор по душам":           RightAnsw,
	"беседа по душам":             RightAnsw,
	"крепкий орешек":              RightAnsw,
	"had been going":              RightAnsw,
	"would be":                    RightAnsw,
	"журнальный столик":           RightAnsw,
	"журнальный стол":             RightAnsw,
	"лекарственное растение":      RightAnsw,
	"бархатное платье":            RightAnsw,
	"повторение - мать учения":    RightAnsw,
	"всё тайное становится явным": RightAnsw,
	"гайка":      RightAnsw,
	"мама":       RightAnsw,
	"мать":       RightAnsw,
	"каблук":     RightAnsw,
	"абзац":      RightAnsw,
	"приступить": RightAnsw,
	"приступать": RightAnsw,
	"начать":     RightAnsw,
	"начинать":   RightAnsw,
	"влиять":     RightAnsw,
	"обещать":    RightAnsw,
	"пообещать":  RightAnsw,
	"jahre alt":  RightAnsw,
	"element":    RightAnsw,
	"проще сказать, чем сделать": RightAnsw,
	"laut":             RightAnsw,
	"банка":            RightAnsw,
	"консервная банка": RightAnsw,
	"встреча":          RightAnsw,
	"собор":            RightAnsw,
	"в чужой монастырь со своим уставом не ходят": RightAnsw,
}
